name: flutter_bugly
description: Flutter plugin for Tencent Bugly, Crash monitoring, Crash analysis, exception reporting, application update, data statistics, etc
version: 1.0.7
homepage: https://github.com/crazecoder/flutter_bugly
# author: crazecoder <21527312@qq.com>

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.crazecoder.flutterbugly
        pluginClass: FlutterBuglyPlugin
      ios:
        pluginClass: FlutterBuglyPlugin
      ohos:
        pluginClass: FlutterBuglyPlugin
